spring:
  profiles:
    active: dev
    include: quartz
  tomcat:
    uri-encoding: utf-8
  servlet:
    context-path: /
  mybatis-plus:
    mapper-locations: classpath*:com/pcitc/hr/**/mapper/xml/*Mapper.xml
    global-config:
      # 主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
      id-type: 2
      # 字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
      field-strategy: 2
      # 驼峰下划线转换
      db-column-underline: true
      # 刷新mapper 调试神器
      refresh-mapper: true
    configuration:
      map-underscore-to-camel-case: true
      cache-enabled: false
jwt:
  header: Authorization
  secret: mySecret
  expiration: 604800
  route.authentication.path: /auth
  route.authentication.refresh: /refresh
servlet:
  multipart:
    enabled: true
    max-file-size: 30MB
    max-request-size: 30MB
#jasypt:
#  encryptor:
#    password: hr!@#$








